config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :searches, only: %i[index new create]
  resources :uploads, only: %i[create new]

  resources :customers, only: %i[index show] do
    resources :payments, path: 'reports', as: 'reports', only: %i[show]
  end

  root to: 'uploads#new'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  has_many :payments, dependent: :destroy
  has_many :lines, through: :payments
  validates :name, presence: true
end

app/models/line.rb
# frozen_string_literal: true

class Line < ApplicationRecord
  belongs_to :payment
end

app/models/payment.rb
# frozen_string_literal: true

class Payment < ApplicationRecord
  belongs_to :customer
  has_many :lines, dependent: :destroy
  has_many :uploads, dependent: :destroy
end

app/models/search.rb
# frozen_string_literal: true

class Search < ApplicationRecord
end

app/models/upload.rb
# frozen_string_literal: true

class Upload < ApplicationRecord
  belongs_to :report
  has_one_attached :report
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
# frozen_string_literal: true

class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.includes(:payments).find(params[:id])
    @reports = @customer.payments.order(date: :desc)
  end

  private

  def customer_params
    params.require(:customer).permit(:name)
  end
end

app/controllers/payments_controller.rb
# frozen_string_literal: true

class PaymentsController < ApplicationController
  def show
    @payment = Payment.find(params[:id])
  end
end

app/controllers/searches_controller.rb
# frozen_string_literal: true

class SearchesController < ApplicationController
  def index
    @searches = Search.all
    @search = @searches.last
    @reports = SearchService.query
  end

  def new
    @search = Search.new
  end

  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to searches_path }
      else
        format.html { render :new }
      end
    end
  end

  private

  def search_params
    params.require(:search).permit(:term)
  end
end

app/controllers/uploads_controller.rb
# frozen_string_literal: true

class UploadsController < ApplicationController
  def new
    @upload = Upload.new
  end

  def create
    @upload = Upload.create(upload_params)
    ProcessReportJob.perform_later @upload.id
    redirect_to new_upload_path, notice: 'We are processing your report!'
  end

  private

  def upload_params
    params.require(:upload).permit(:report)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def no_data?
    Customer.count.zero?
  end
end

app/views/customers/index.html.erb
<% if no_data? %>
  <%= render 'shared/no_data' %>
<% else -%>
  <h1 class='title'>Customers</h1>

  <div class="section">
    <% @customers.each do |customer| %>
      <h2 class='title'>
        <%= link_to customer.name, customer %>
      </h2>
    <% end %>
  </div>
<% end -%>

app/views/customers/show.html.erb
<div class="section">
  <h2 class='title'>
    <%= @customer.name %>
  </h2>
  <div class="columns">
    <div class="column">
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi ut et eveniet aliquam, porro eos suscipit assumenda, enim tenetur sapiente, dolores quos. Tenetur eos, illum! Reprehenderit alias est itaque debitis.
      </p>
    </div>
    <div class="column reports">
      <h2 class="title">Reports</h2>
        <% @reports.each do |p| %>
          <h3 class='title'><%= link_to p.report_date, customer_report_path(p) %></h3>
        <% end -%>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReportReader</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="section">
      <%= render 'shared/nav' %>
    </header>
    <main class='main'>
      <%= render 'shared/notice' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/payments/_form.html.erb
<%= form_with(model: payment, local: true) do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :page %>
    <%= form.text_field :page %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.text_field :customer_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Page</th>
      <th>Code</th>
      <th>Description</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.date %></td>
        <td><%= payment.page %></td>
        <td><%= payment.code %></td>
        <td><%= payment.description %></td>
        <td><%= payment.customer_id %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<h1 class="title">
  <%= link_to @payment.customer.name, @payment.customer %>
</h1>

<div class="columns">
  <div class="column is-7">
      <table class='table is-fullwidth'>
        <tr>
          <td>Report Date</td>
          <td class='has-text-right'><%= @payment.report_date%>
          </td>
        </tr>
        <tr>
          <td>Report Name</td>
          <td class='has-text-right'><%= @payment.report_name %></td>
        </tr>
        <tr>
          <td>Codes</td>
          <td class='has-text-right'><%= @payment.code %></td>
        </tr>
        </tr>
      </table>
  </div>
  <div class="column is-5">
    <% @payment.uploads.each do |img| %>
    <div class="box">
      <%= image_tag img.report  %>
      <%= link_to 'download', img.report, download: true, class: 'button is-small is-primary' %>
    </div>
    <% end %>
  </div>
</div>

app/views/searches/index.html.erb
<h1 class='title'>Search Results</h1>
<div class="columns">
  <div class="column">
    <% if @search.present? && @reports.present?  %>
      <% @reports.each do |q| %>
        <%= link_to "report", customer_report_path(q, q.id) %>
      <% end  %>
    <% else  %>
      <div>
        Sorry, no reports match<%= @search.nil? ? "." : " #{@search.term}" %>
      </div>
    <% end -%>
  </div>
  <div class="column">
    <h2 class='sub-title'>Recent Searches</h2>
    <ul>
      <% @searches.each do |search| %>
        <li>
          <%= search.term %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/searches/new.html.erb
<% if no_data? %>
  <%= render 'shared/no_data' %>
<% else -%>
  <h1 class='title'>Search Reports</h1>

  <%= form_with(model: @search, local: true) do |form| %>
    <% if @search.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@search.errors.count, "error") %> prohibited this @search from being saved:</h2>

        <ul>
          <% @search.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="columns">
      <div class="column">
        <div class="field">
          <%= form.text_field :term, class: 'input' %>
        </div>
      </div>
      <div class="column">
        <div class="actions">
          <%= form.submit class: 'button is-primary' %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar is-transparent">
  <div class="navbar-brand">
    <div class='title'>
      <%= link_to 'RPRT$', '/' %>
    </div>
    <div><%= link_to 'customers', customers_path, class: "navbar-item" %></div>
    <div><%= link_to 'upload', new_upload_path, class: "navbar-item" %></div>
    <div><%= link_to 'search', new_search_path, class: "navbar-item" %></div>
  </div>
</nav>

app/views/shared/_no_data.html.erb
<h1 class='title'>
  No <%= controller_name %> yet...
</h1>

<p class='sub-title'>
  <%= link_to 'Upload report', new_upload_path, class: "button" %>
</p>

app/views/shared/_notice.html.erb
<% if notice.present? %>
  <div class="notification is-info">
    <p id="notice">
      <%= notice %>
    </p>
  </div>
<% end %>

app/views/uploads/new.html.erb
<h1 class='title'>Upload Report</h1>

<%= form_with(model: @upload, local: true) do |form| %>
  <div class="columns">
    <div class="column">
      <div class="field">
        <%= form.file_field :report %>
      </div>
    </div>
    <div class="column">
      <div class="actions">
        <%= form.submit class: 'button is-primary' %>
      </div>
    </div>
  </div>
<% end %>